version: '3.1'

services:
  datastore:
    image: mongo
    ports:
      - 27017:27017

  database:
    image: postgres
    ports:
      - 5432:5432

  nats:
    image: nats
    ports:
      - 4222:4222

  shipy-user-service:
    build: ./user-service
    ports:
      - 50053:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_BROKER: "nats"
      MICRO_BROKER_ADDRESS: "nats:4222"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    depends_on:
      - database
      - nats

  shipy-user-cli:
    build: ./user-cli
    depends_on:
      - shipy-user-service

  shipy-consignment-cli:
    build: ./consignment-cli
    depends_on:
      - shipy-consignment-service

  shipy-consignment-service:
    build: ./consignment-service
    ports:
      - 50051:50051
    environment:
      WAIT_HOSTS: datastore:27017
      MICRO_ADDRESS: ":50051"
      DB_HOST: "mongodb://datastore:27017"
    depends_on:
      - datastore
      - shipy-user-service

  shipy-vessel-service:
    build: ./vessel-service
    ports:
      - 50052:50051
    environment:
      WAIT_HOSTS: datastore:27017
      MICRO_ADDRESS: ":50051"
      DB_HOST: "mongodb://datastore:27017"
    depends_on:
      - datastore

  shipy-email-service:
    build: ./email-service
    ports:
      - 50054:50054
    environment:
      MICRO_SERVER_ADDRESS: ":50054"
      MICRO_BROKER: "nats"
      MICRO_BROKER_ADDRESS: "nats:4222"
    depends_on:
      - nats

